development:
  adapter: postgresql
  database: tailormade_development
  host: localhost
  username: postgres
  password: postgres
  encoding: utf8

production:
  adapter: postgresql
  database: tailormade
  host: localhost
  username: postgres
  password: postgres
  encoding: utf8

test:
  adapter: postgresql
  database: tailormade_development_test
  host: localhost
  username: postgres
  password: postgres
  encoding: utf8
